# Conclusion

  Our research goals were finding associations between inspection results and locations of restaurants / cuisines. And at the end, sorting some restaurants based on the inspection results could be a reference for our target audiences. 

  All the boroughs have very similar average inspection scores around 23 and distribution. The majority of the cases has similar proportion of grades as the majority of the inspections grades are A (0-13), which are low inspection scores, in all the boroughs. Especially, Staten Island has the highest proportion of grade A and lowest proportion of C, which seems the best result among all the boroughs. According to the chi-square test, there is strong evidence, which is very small p-value, that there is association between inspection results and boroughs or locations. Based on our research objectives, we sought to explore the relationship between the geographical location and the quality metrics—scores and critical flags—of restaurants. Our analysis spanned multiple levels, including individual districts and borough-wide aggregations. From the choropleth map, we observed that some of districts of Queens are marked by lighter shades, indicating lower average scores relative to other boroughs. In addition, the bar chart reflecting annual trends reveals a peak average score of 18 for Queens in 2023. This juxtaposition suggests that the Queens overall has struggled to maintain consistent sanitation quality levels. The interactive map shows the binary classification of good and bad restaurant based on the critical flag proportion. The markers in Manhattan suggests a high density of restaurants in this borough. The presence of both classification in close proximity could imply a wide variance in the adherence to standards within a small geographical area. The density of markers also underscores the competitive and diverse nature of the food industry in Manhattan, where high concentration of dining options coexist. Incorporating D3's interactive functionalities into the map significantly enhances the user experience by providing the ability to zoom in on specific districts. This feature allows user to focus on areas of interest and discern the distribution of restaurants that meet high sanitation standards and avoid those which have cleanliness issue. The targeted view would be particularly beneficial for individuals who prioritize healthliness when dining out. For the cuisines, Indian, Spanish, Latin American, Chinese, and Caribbean got high inspection scores (low inspection scores denote good grades), which would not be satisfiable results for those restaurants. However, Sandwiches, American, Coffee/Tea, Hamburgers, and Donuts got low inspection scores. Compared to the other cuisines, Sandwiches, Coffee/Tea, Hamburgers, and Donuts are easier to make than other cuisines, so it is understandable that they have less chance to have problems related to sanity/cleanliness. According to the chi-square test, there is strong evidence, which is very small p-value, that there is association between inspection results and cuisines.

  We could find some meaningful associations between inspection results and locations of restaurants / cuisines. We could also visualize restaurants which have low critical flag proportion and high critical flag proportion by different colors on the NYC map. At the end of the result part, the wordcloud visualization about the violation descriptions from the restaurants that got high inspection scores and high critical flag proportion would help audiences to understand some key words about their violations.

