# Introduction

  As a current resident in NYC, it is very hard to choose which restaurant to go among countless restaurants in NYC. It might be harder to choose restaurants in NYC to some people, who care about sanitation a lot because of some health issues. The dataset, which includes NYC restaurant and college cafeteria inspection results for up to three years prior to the most recent inspection, can provide information on recent inspection results of current NYC restaurants. This project can be helpful for deciding which restaurants to be visited or not to be visited, especially to people who need to care a lot about their diets and cleanliness.

The main questions of this project is finding relationship between inspection result (scores, critical flag, legal action) and locations/cuisines.

* Are inspection results, especially scores and critical flag, related to locations? Let's visualize some restaurants by using critical flag proportion on the map for the target audiences.

* Are inspection results, especially scores, related to cuisines? 

* Chain restaurants have worse inspection scores than independent restaurants?

The dataset contains every sustained or not yet adjudicated violation citation from every full or special food inspection conducted up to three years prior to the most recent inspection for restaurants and college cafeterias in an active status on the RECORD DATE. So only restaurants in an active status are included in the dataset. Restaurants, which have more than one violation in inspection, values for associated fields are repeated for each additional violation record, and each cases are differentiated by their CAMIS (record ID) number. Restaurants, that has applied for a permit but has not yet been inspected and for inspections, result in no violations. Inspection date of 1/1/1900 are new establishments that have not yet received an inspection. Restaurants that received no violations are represented by a single row and coded as having no violations using the ACTION field. The inspection program allows for a two-step inspection process, providing an opportunity for restaurants who do not receive an “A” on their initial inspection to be re-inspected.  This re-inspection occurs no less than 7 days after the initial inspection. 

Note that 

1) After the inspections, restaurants can go through the adjudication process or argue their case at an administrative hearing.

2) Restaurants have appeal rights that the entire adjudication process can take several months. 

3) Scores current as of today may be revised due to adjudication. 

4) Since restaurants out of business are removed, this project is not about comparison with the past inspection results for NYC restaurants. Also, the score can be revised due to adjudication, it is not valid to compare current scores to scores from previous years. 

5) Letter grading inspections were put on pause from March 17, 2020 to July 19, 2021, due to the COVID-19 public health emergency. Modified restaurant inspections occurred during this time.   


